import test from 'node:test';
import assert from 'node:assert/strict';
import { chatWindow } from '../lib/chat-schedule.ts';
const base={now:1800000000000,coinId:'schedule-test',launched:true,paused:false,balanceWei:1000n,thresholdWei:100n,fundedMicrousd24h:1000000,fundingVerified:true,observedAt:1800000000000,creditMicrousd:1000000,questionCeilingMicrousd:10000};
test('funding flow sets limited hourly, four-hourly and daily sessions',()=>{assert.equal(chatWindow(base).cadence,'hourly');assert.equal(chatWindow({...base,fundedMicrousd24h:200000}).cadence,'four-hourly');assert.equal(chatWindow({...base,fundedMicrousd24h:20000}).cadence,'daily');for(const flow of [0,100000,1000000,10000000])assert.ok(chatWindow({...base,fundedMicrousd24h:flow}).durationMinutes<=20)});
test('exact closing time is excluded and opening time is included',()=>{const initial=chatWindow(base),start=initial.open?initial.closesAt-initial.durationMinutes*60000:initial.nextOpensAt;assert.equal(chatWindow({...base,now:start,observedAt:start}).open,true);assert.equal(chatWindow({...base,now:start+initial.durationMinutes*60000,observedAt:start}).open,false)});
test('spending or refunds cannot select a new cadence',()=>{const high=chatWindow(base),lower=chatWindow({...base,creditMicrousd:10001});assert.equal(high.cadence,lower.cadence);assert.equal(high.nextOpensAt,lower.nextOpensAt);assert.equal(high.closesAt,lower.closesAt)});
test('pause, worker closure, stale balance or missing funding shut chat',()=>{for(const override of [{paused:true},{closedUntil:base.now+1000},{observedAt:base.now-7200001},{fundingVerified:false},{balanceWei:50n},{creditMicrousd:0},{launched:false}]){const r=chatWindow({...base,...override});assert.equal(r.open,false);assert.equal(r.cadence,'closed');assert.equal(r.nextOpensAt,null)}});
test('repeated reads do not renew the session',()=>assert.deepEqual(chatWindow(base),chatWindow(base)));
