'use client';
import { useEffect, useState } from 'react';
import { ArrowUpRight, Globe2, RefreshCw } from 'lucide-react';
import type { Coin } from '@/lib/model';
import type { PublishedWebsite } from '@/lib/website-policy';
import type { T } from '@/lib/ui';
import type {PublicDomain} from '@/lib/custom-domains';

export default function AgentWebsite({coin,t}:{coin:Coin;t:T}){
 const [site,setSite]=useState<PublishedWebsite|null>(null),[domain,setDomain]=useState<PublicDomain|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[refresh,setRefresh]=useState(0);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');
  fetch(`/api/coins/${coin.id}/website`,{signal:controller.signal}).then(async r=>{const data=await r.json() as {site:PublishedWebsite|null;domain:PublicDomain|null;error?:string};if(!r.ok)throw Error(data.error||'Could not load website.');setSite(data.site);setDomain(data.domain)}).catch(e=>{if(!controller.signal.aborted)setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});
  return()=>controller.abort();
 },[coin.id,refresh]);
 const progressLabels={pricing:t('检查域名与价格','Checking availability and price'),funding:t('安排域名资金','Funding the domain'),registering:t('正在注册域名','Registering the domain'),renewing:t('正在续费域名','Renewing the domain'),connecting:t('连接域名与网站','Connecting the website'),review:t('等待确认','Awaiting confirmation')};
 return <div className="panel hosted-site-panel"><div className="panel-heading"><h2>{t('社区网站','Community website')}</h2><button type="button" className="website-refresh" aria-label={t('刷新网站状态','Refresh website status')} disabled={loading} onClick={()=>setRefresh(v=>v+1)}><RefreshCw size={16} className={loading?'spin':''}/></button></div>
 {error?<p role="alert" className="form-error">{error}</p>:site?<><div className={'hosted-site-preview theme-'+site.theme}><div className="hosted-site-status"><span/>{t('已发布','PUBLISHED')}<small>V{site.revision.toString().padStart(2,'0')}</small></div><span className="overline">${coin.symbol} / {t('社区','COMMUNITY')}</span><h2>{site.title}</h2><p>{site.tagline}</p><a href={site.url} target="_blank" rel="noreferrer" className="button primary">{t('访问网站','Visit website')}<ArrowUpRight size={17}/></a></div><div className="hosted-site-meta"><span>{t('由智能体创建并维护','Created and maintained by the agent')}</span><time dateTime={new Date(site.publishedAt).toISOString()}>{new Date(site.publishedAt).toLocaleString()}</time></div></>:<div className="empty-state"><Globe2 size={30}/><h3>{loading?t('正在加载网站…','Loading website…'):t('尚未发布网站','No website published yet')}</h3><p>{coin.website?t('累计费用收入约达 500–600 美元时，智能体通常会优先考虑创建网站，并结合可用资金与运行成本决定时机。这是参考收入目标，不是建站花费。','The agent usually prioritizes a website around $500–$600 in collected fees, subject to available funds and operating costs. This is an approximate revenue target, not the cost of the website.'):t('此智能体未启用社区网站。','A community website was not selected for this agent.')}</p></div>}
 {domain&&site&&!error&&<section className="panel" style={{marginTop:24,padding:24}} aria-label={t('独立域名','Custom domain')}><div className="panel-heading"><h3>{t('独立域名','Custom domain')}</h3><span className={'status '+(domain.state==='live'?'active':'dormant')}>{domain.state==='live'?t('已连接','Connected'):domain.state==='degraded'?t('等待处理','Needs attention'):domain.registered?t('配置中','Connecting'):t('准备中','In progress')}</span></div><p style={{fontSize:20,overflowWrap:'anywhere',margin:'16px 0'}}>{domain.domain}</p>{domain.progress&&<p className="hosted-site-meta" role="status" style={{margin:'0 0 18px'}}>{progressLabels[domain.progress]}</p>}{domain.state==='live'?<a className="button secondary" href={'https://'+domain.domain} target="_blank" rel="noreferrer">{t('打开独立网站','Open custom website')}<ArrowUpRight size={16}/></a>:<p style={{color:'var(--muted-foreground)',fontSize:13,lineHeight:1.7}}>{domain.state==='degraded'?t('域名连接或续费需要处理。QI 网站仍然可用。','The domain connection or renewal needs attention. Your QI website remains available.'):t('域名正在准备中。你仍然可以访问上方的 QI 网站。','The domain is being prepared. Your QI website remains available above.')}</p>}<div className="hosted-site-meta"><span>{t('通过 QI 的托管账户管理域名','Managed through QI’s registrar account')}</span>{domain.expiresAt&&<span>{t('到期日期','Registration expires')} {new Date(domain.expiresAt).toISOString().slice(0,10)}</span>}</div></section>}
 </div>;
}
