"use client";
import { useEffect, useState } from 'react';
import { Terminal, Database } from 'lucide-react';
import type { T } from '@/lib/ui';
type Snapshot = { state: string; changedAt: number | null; observedAt: number; workerSeenAt: number | null; nextCheckAt: number | null; memory: { entries: number; updatedAt: number | null }; events: { id: string; message: string; createdAt: string }[] };
export default function LiveAgentConsole({ coinId, t }: { coinId: string; t: T }) {
  const [value, setValue] = useState<Snapshot | null>(null), [error, setError] = useState(false);
  useEffect(() => { let active = true; const controller = new AbortController(); async function load() { try { const r = await fetch(`/api/coins/${coinId}/console`, { signal: controller.signal }); if (!r.ok) throw Error(); const data = await r.json() as Snapshot; if (active) { setValue(data); setError(false); } } catch { if (active) setError(true); } } setValue(null); void load(); const timer = setInterval(() => { if (!document.hidden) void load(); }, 10000); return () => { active = false; controller.abort(); clearInterval(timer); }; }, [coinId]);
  const states: Record<string, string> = { scheduled: t('等待下一次检查', 'Between work cycles'), awaiting_launch: t('等待发行', 'Awaiting launch'), worker_unconfirmed: t('运行状态未确认', 'Worker status unconfirmed'), researching: t('正在搜索来源', 'Searching public sources'), funding_services: t('服务付款处理中', 'Service payment pending'), transaction_pending: t('等待交易确认', 'Waiting for a transaction'), verification_pending: t('等待结果核实', 'Result needs verification'), posting: t('正在提交 X 帖子', 'Submitting an X post'), creating_image: t('正在生成图片', 'Generating artwork'), publication_queued: t('内容队列处理中', 'Publication in progress'), domain_pending: t('域名流程处理中', 'Domain workflow pending'), planning: t('正在制定计划', 'Planning its next actions'), awaiting_funds: t('等待金库资金', 'Awaiting treasury funding'), checking: t('正在检查资金与服务', 'Checking funds and services') };
  return <section className="panel live-console"><div className="live-console-heading"><Terminal size={18}/><span>{t('智能体控制台', 'AGENT CONSOLE')}</span><small>{t('只读', 'READ ONLY')}</small></div><div className="live-console-state"><span className="overline">{t('当前记录', 'CURRENT RECORD')}</span><h3>{error ? t('更新暂不可用', 'Updates unavailable') : value ? states[value.state] ?? t('状态待确认', 'Status unconfirmed') : t('正在读取…', 'Loading…')}</h3>{value && <p>{t('检查时间', 'Checked')} {new Date(value.observedAt).toLocaleTimeString()}{value.nextCheckAt && <> · {t('下次周期', 'Next cycle')} {new Date(value.nextCheckAt).toLocaleTimeString()}</>}</p>}</div><div className="live-console-log" role="log" aria-label={t('已记录的活动', 'Recorded activity')}>{value?.events.length ? value.events.map(e => <div key={e.id}><time dateTime={e.createdAt}>{new Date(e.createdAt).toLocaleString()}</time><p>{e.message}</p></div>) : <p className="live-console-empty">{t('尚无已记录的活动。', 'No recorded activity yet.')}</p>}</div><div className="live-console-memory"><Database size={14}/><span>{t('持久记忆', 'Persistent memory')} · {value?.memory.entries ?? 0} {t('条计划记录', 'plan records')}</span><small>{t('每 10 秒刷新', 'Refreshes every 10s')}</small></div></section>;
}
