"use client";
import { useEffect,useState } from 'react';
import { formatEther } from 'viem';
import type { T } from '@/lib/ui';
type Record={conversions?:{id:string;quoteToken:string;amountUnits:string;outputWei:string;phase:string;transactions:{hash:string;kind:string;status:string}[]}[];enabled:boolean;tokenAddress:string|null;fees:{distributedWei:string;observedAt:number}|null;campaigns:{id:string;amountWei:string;status:string;stage:string;transactions:{hash:string;kind:string;status:string}[]}[]};
export default function ProtocolFees({coinId,t}:{coinId:string;t:T}){
 const [record,setRecord]=useState<Record|null>(null),[error,setError]=useState(false);
 useEffect(()=>{let alive=true;const controller=new AbortController();async function load(){try{const r=await fetch(`/api/coins/${coinId}/protocol`,{signal:controller.signal});if(!r.ok)throw Error();const v=await r.json() as Record;if(alive){setRecord(v);setError(false);}}catch{if(alive)setError(true);}}void load();const timer=setInterval(()=>{if(!document.hidden)void load();},30000);return()=>{alive=false;controller.abort();clearInterval(timer);};},[coinId]);
 return <section className="panel"><div className="panel-heading"><h2>{t('SHEN 协议回购','SHEN protocol buybacks')}</h2><span className="overline">15% · AUTOMATED</span></div><p className="body-copy">{t('平台自动将已确认费用收入的 15% 留作 SHEN 回购并转入销毁地址；智能体使用其余 85% 支付成本并管理本币。存入金库的普通资金不计作费用。','The platform reserves 15% of confirmed fee revenue for SHEN buybacks and burn-sink transfers. The agent uses the remaining 85% for costs and its own token. Ordinary treasury deposits are excluded.')}</p>{error?<p role="status">{t('协议记录暂不可用。','Protocol records are temporarily unavailable.')}</p>:record&&<><p className="body-copy">{record.enabled?t('系统分批执行，资金不足时继续累积。','The system executes in batches; smaller allocations continue accumulating.'):t('分配持续保留，等待平台配置与执行条件就绪。','Allocations remain reserved while platform configuration and execution conditions are pending.')}</p>{!!record.conversions?.length&&<div><h3>Quote fees → BNB</h3>{record.conversions.map(c=><article className="treasury-operation" key={c.id}><strong>{c.phase==='complete'?formatEther(BigInt(c.outputWei))+' BNB converted':c.phase==='unwrap'?'Unwrapping verified WBNB proceeds':c.phase}</strong><p className="body-copy">Pair token: {c.quoteToken}</p><div className="operation-receipts">{c.transactions.map(tx=><a key={tx.hash} href={'https://bscscan.com/tx/'+tx.hash} target="_blank" rel="noreferrer" className="text-link">{tx.kind.replace('convert_','')} · {tx.status} ↗</a>)}</div></article>)}</div>}{record.campaigns.map(c=><article className="treasury-operation" key={c.id}><div className="publication-meta"><strong>{formatEther(BigInt(c.amountWei))} BNB → $SHEN</strong><span className="overline">{c.status} · {c.stage}</span></div><div className="operation-receipts">{c.transactions.map(tx=><a key={tx.hash} className="text-link" href={`https://bscscan.com/tx/${tx.hash}`} target="_blank" rel="noopener noreferrer">{tx.kind==='burn'?t('销毁转账','Burn-sink transfer'):t('SHEN 回购','SHEN purchase')} · {tx.status} ↗</a>)}</div></article>)}{!record.campaigns.length&&<p className="body-copy">{t('尚无协议回购交易。','No protocol buyback transactions yet.')}</p>}</>}</section>;
}
