"use client";
import {useEffect,useState} from 'react';
import {QUOTE_CATALOG} from '@/shared/quote-catalog.mjs';
export default function QuoteTokenPicker({value,onChange,disabled}:{value:string;onChange:(address:string)=>void;disabled:boolean}){
 const [category,setCategory]=useState('crypto'),[search,setSearch]=useState(''),[custom,setCustom]=useState(''),[status,setStatus]=useState(''),[symbol,setSymbol]=useState('BNB'),[gas,setGas]=useState('');
 useEffect(()=>{let alive=true;setStatus('Checking Flap eligibility and conversion route…');void fetch('/api/quote-tokens?address='+encodeURIComponent(value)).then(async r=>({ok:r.ok,body:await r.json() as {token?:{symbol:string};gasDepositBnb?:string;error?:string}})).then(({ok,body})=>{if(alive){setStatus(ok?'Eligible pair · checked again before launch':body.error??'Pair unavailable');setSymbol(body.token?.symbol??'Selected token');setGas(body.gasDepositBnb??'')}}).catch(()=>{if(alive)setStatus('Pair check unavailable; retry before launching.')});return()=>{alive=false}},[value]);
 const tokens=QUOTE_CATALOG.filter(t=>(category==='all'||t.category===category)&&`${t.symbol} ${t.name} ${t.address}`.toLowerCase().includes(search.toLowerCase()));
 return <div className="form-field span-two"><span>Pair token · {symbol}</span><div className="filter-tabs" style={{display:'flex',gap:8,flexWrap:'wrap'}}>{[['crypto','Crypto'],['stocks','Stocks'],['pre-ipo','Pre-IPO'],['all','All']].map(([id,label])=><button type="button" className={'button secondary'+(category===id?' active':'')} disabled={disabled} key={id} onClick={()=>setCategory(id)}>{label}</button>)}</div>
 <input aria-label="Search pair tokens" placeholder="Search tokens" value={search} disabled={disabled} onChange={e=>setSearch(e.target.value)}/>
 <select aria-label="Pair token" value={value} disabled={disabled} onChange={e=>onChange(e.target.value)}>{!tokens.some(t=>t.address.toLowerCase()===value.toLowerCase())&&<option value={value}>{symbol} · {value}</option>}{tokens.map(t=><option value={t.address.toLowerCase()} key={t.address}>{t.symbol} — {t.name}</option>)}</select>
 <div style={{display:'flex',gap:8}}><input aria-label="Custom pair contract address" placeholder="Or enter a supported BNB Chain contract address" value={custom} disabled={disabled} onChange={e=>setCustom(e.target.value.trim())}/><button type="button" className="button secondary" disabled={disabled||!/^0x[0-9a-fA-F]{40}$/.test(custom)} onClick={()=>onChange(custom.toLowerCase())}>Check</button></div>
 <small role="status">{status}</small><small>Stock and pre-IPO options are tokenized assets. Non-BNB pairs require a separate BNB gas deposit sent directly to the agent. After the token launches, you approve this deposit in your wallet. {gas&&gas!=='0'?`Estimated deposit: ${gas} BNB, plus network gas.`:''}</small></div>;
}
