"use client";
import { useEffect, useState, type FormEvent } from 'react';
import { Check, LockKeyhole, LoaderCircle, ArrowUpRight } from 'lucide-react';
import type { T } from '@/lib/ui';
type Status={configured:boolean;connected:boolean;username:string|null;pending:{id:string;status:string}|null;message?:string;error?:string};
export default function SocialConnection({coinId,t}:{coinId:string;t:T}){
 const [status,setStatus]=useState<Status|null>(null),[busy,setBusy]=useState(false),[editing,setEditing]=useState(false),[error,setError]=useState('');
 const [username,setUsername]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[totpSecret,setTotpSecret]=useState(''),[consent,setConsent]=useState(false);
 useEffect(()=>{let alive=true;fetch(`/api/coins/${coinId}/social`).then(r=>r.json() as Promise<Status>).then(v=>{if(alive){if(v.error)setError(v.error);else{setStatus(v);if(v.username)setUsername(v.username)}}}).catch(()=>{if(alive)setError('Could not check the X account.')});return()=>{alive=false}},[coinId]);
 async function submit(e?:FormEvent,check=false){e?.preventDefault();setBusy(true);setError('');try{const r=await fetch(`/api/coins/${coinId}/social`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(check?{action:'check',id:status?.pending?.id}:{action:'connect',username:username.replace(/^@/,''),email,password,...(totpSecret?{totpSecret}:{}),consent})});const v=await r.json() as Status;if(!r.ok)throw Error(v.error);setStatus(v);if(v.connected){setEditing(false);window.dispatchEvent(new Event('shen-x-connected'))}if(v.message)setError(v.message)}catch(e){setError((e as Error).message)}finally{setPassword('');setTotpSecret('');setBusy(false)}}
 return <section className="panel x-connection"><div className="panel-heading"><h2><span className="x-mark">𝕏</span>{t('社区账号','Community account')}</h2><span className={'status '+(status?.connected?'active':'dormant')}>{status?.connected?t('已连接','Connected'):t('设置','Setup')}</span></div>
  <p className="body-copy">{t('连接你为此代币创建的 X 账号。发行并获得资金后，智能体自主决定何时发布更新与图片。','Connect the X account you created for this coin. After launch and funding, the agent decides when to publish updates and artwork.')}</p>
  {status?.connected&&<div className="x-connected"><Check size={18}/><a href={'https://x.com/'+status.username} target="_blank" rel="noreferrer">@{status.username}<ArrowUpRight size={15}/></a><button type="button" className="text-link" onClick={()=>setEditing(!editing)}>{t('更新账号授权','Refresh account access')}</button></div>}
  {status&&!status.configured&&<div className="subtle-note"><LockKeyhole size={17}/>{t('账号接入暂不可用。服务就绪后可在这里连接。','Account setup is unavailable until the posting service is configured.')}</div>}
  {status?.pending?<div className="x-verifying"><p>{t('正在确认账号验证帖。重试检查不会再次发帖。','The account verification post is awaiting confirmation. Checking again does not send another post.')}</p><button className="button secondary" disabled={busy} onClick={()=>void submit(undefined,true)}>{busy?<LoaderCircle size={15} className="spin"/>:<Check size={15}/>} {t('检查连接','Check connection')}</button></div>:status?.configured&&(!status.connected||editing)&&<form className="x-form" onSubmit={submit}>
   <div className="form-grid"><label className="form-field">{t('X 用户名','X username')}<input required maxLength={15} autoComplete="off" value={username} onChange={e=>setUsername(e.target.value.replace(/^@/,''))}/></label><label className="form-field">{t('账号邮箱','Account email')}<input required type="email" autoComplete="off" value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="form-field">{t('账号密码','Account password')}<input required type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><label className="form-field">{t('双重验证密钥（推荐）','2FA setup key (recommended)')}<input type="password" autoComplete="off" value={totpSecret} onChange={e=>setTotpSecret(e.target.value.replace(/\s/g,''))}/><small>{t('使用设置 2FA 时的 Base32 密钥，不是 6 位验证码。','The Base32 setup key from 2FA enrollment, not a six-digit code.')}</small></label></div>
   <div className="subtle-note"><LockKeyhole size={17}/><p>{t('连接使用 TwitterAPI.io 验证账号。密码与 2FA 密钥仅用于本次登录，不会保存。加密的账号会话用于后续发布。','TwitterAPI.io verifies the account. Your password and 2FA key are used for this login and are not stored. The resulting account session is encrypted for future posting.')}</p></div>
   <label className="x-consent"><input required type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>{t('我拥有此账号，并授权发送一条公开的 SHEN 验证帖以确认账号控制权；发行后由智能体自主发布。','I control this account and authorize one public SHEN verification post to confirm access, followed by autonomous agent posts after launch.')}</span></label>
   <button className="button primary" type="submit" disabled={busy||!consent}>{busy?<LoaderCircle size={16} className="spin"/>:<span>𝕏</span>}{busy?t('正在验证…','Verifying…'):t('连接并验证账号','Connect & verify account')}</button>
  </form>}
  {error&&<p className="form-error" role="status">{error}</p>}
 </section>
}
