"use client";
import Link from "next/link";
import { Globe2, ImageIcon, Search, Radio, Zap } from "lucide-react";
import type { Coin, Language } from "@/lib/model";
import { stateLabel, type T } from "@/lib/ui";
import TokenChart from "./token-chart";
export default function TokenCard({coin:c,t,index=0,preview=false}:{coin:Coin;lang:Language;t:T;index?:number;preview?:boolean}){
 const content=<><div className="card-caption"><span>AGENT_{String(index+1).padStart(3,"0")}</span><span className={"status "+c.state}>{c.state==="active"?<Zap size={11}/>:<span className="status-square"/>}{stateLabel(c,t)}</span></div><div className="card-identity"><div className={"coin-mark "+(c.color??"")} translate="no">{c.imageUrl?<img src={c.imageUrl} alt={c.name+" token"}/>:c.symbol.slice(0,2)||"?"}</div><div><h3>{c.name||t("你的代币","Your token")}</h3><span className="ticker">${c.symbol||"TICKER"}</span></div><span className="card-chain">BNB<br/><span>56</span></span></div><p className="card-story">{c.description||t("你的社区故事从这里开始。","Your community's story starts here.")}</p><div className="card-funding"><div><span className="overline">{t("智能体金库","AGENT TREASURY")}</span><strong>{c.balance.toFixed(3)}<small>BNB</small></strong></div><div className="card-chart">{c.tokenAddress?<TokenChart coinId={c.id} compact t={t}/>:<span className="no-data">{t("尚未发行","PRE-LAUNCH")}</span>}</div></div><div className="funding-caption"><span>{c.state==="active"?t("已超过启动门槛","Activation threshold met"):t("启动目标","Activation target")}</span><span>{Math.min(100,Math.round(c.balance/c.threshold*100))}%</span></div><div className="funding-track"><i style={{width:Math.min(100,c.balance/c.threshold*100)+"%"}}/></div><div className="card-footer"><div className="capability-icons">{[[Search,c.research,"Research"],[Radio,c.social,"Social"],[Globe2,c.website,"Website"],[ImageIcon,c.images,"Images"]].map(([Icon,on,label])=>{const I=Icon as typeof Search;return <span key={String(label)} className={on?"":"off"} title={String(label)}><I size={14}/></span>})}</div><span>{c.language==="zh"?"中文":"EN"}<b> / </b>{c.taxRate}% {t("交易税","tax")}</span></div></>;
 return preview?<article className={"agent-card preview "+(c.color??"")}>{content}</article>:<Link href={"/token/"+c.id} className={"agent-card "+(c.color??"")}>{content}</Link>
}
