"use client";
import { VOICES, FOCUSES, characterLabel } from "@/lib/agent-character";
import { coinPath } from "@/lib/coin-links";
import LiveAgentConsole from "./live-agent-console";
import ResearchFeed from "./research-feed";
import { useEffect, useState } from "react";
import Link from "next/link";
import { Bot, ShieldCheck, Globe2, Search, Radio, ImageIcon, ExternalLink, Copy, Activity } from "lucide-react";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { toast } from "sonner";
import type { Coin, Language } from "@/lib/model";
import { stateLabel, type T } from "@/lib/ui";
import { agentModel, DEFAULT_AGENT_PURPOSE } from "@/lib/agent-models";
import FlapLaunch from "./flap-launch";
import AgentChat from "./agent-chat";
import ModelLogo from "./model-logo";
import TokenChart from "./token-chart";
import SocialConnection from "./social-connection";
import CommunityFeed from "./community-feed";
import ProtocolFees from "./protocol-fees";
import TreasuryOperations from './treasury-operations';
import AgentWebsite from "./agent-website";

export default function TokenView({coin:initial,t,canManage=false}:{coin:Coin;lang:Language;t:T;canManage?:boolean}){
 const [coin,setCoin]=useState(initial),[events,setEvents]=useState<{id:string;message:string;createdAt:string}[]>([]),[eventError,setEventError]=useState("");
 useEffect(()=>{let active=true;fetch("/api/coins/"+coin.id+"/events").then(async r=>{const data=await r.json() as {events:typeof events;error?:string};if(!r.ok)throw Error(data.error);if(active)setEvents(data.events)}).catch(e=>{if(active)setEventError(e.message)});return()=>{active=false}},[coin.id]);
 const launched=!!coin.tokenAddress;
 return <><div className="breadcrumb"><Link href="/">{t("探索","Discover")}</Link><span>/</span><span>${coin.symbol}</span><span className="right-label">{launched?"BNB CHAIN":"LAUNCH PLAN"}</span></div><div className="token-page-heading"><div className={"coin-mark large "+(coin.color??"")}>{coin.imageUrl?<img src={coin.imageUrl} alt={coin.name+" token"}/>:coin.symbol.slice(0,2)}</div><div><div className="token-heading-line"><h1>{coin.name}</h1><span className={"status "+coin.state}>{stateLabel(coin,t)}</span></div><div className="token-meta"><span>${coin.symbol}</span><span>BNB CHAIN</span><span>{coin.language==="zh"?"中文 AGENT":"ENGLISH AGENT"}</span></div></div><div className="token-heading-actions"><button className="button secondary" onClick={async()=>{try{await navigator.clipboard.writeText(window.location.origin+coinPath(coin.id));toast.success(t("链接已复制","Link copied"))}catch{toast.error(t("无法复制链接","Could not copy link"))}}}><Copy size={14}/>{t("分享","Share")}</button>{launched&&<a href={"https://flap.sh/bnb/"+coin.tokenAddress} target="_blank" rel="noreferrer" className="button primary">Flap <ExternalLink size={14}/></a>}</div></div><p className="token-page-description">{coin.description}</p>
 <div className="token-page-layout"><div className="token-primary"><div className="token-metrics">{[[t("最近确认的金库余额","Last confirmed treasury"),coin.balance.toFixed(3),"BNB"],[t("启动门槛","Activation threshold"),String(coin.threshold),"BNB"],[t("交易税","Trading tax"),String(coin.taxRate),"%"]].map(([label,value,unit])=><div key={label}><span className="overline">{label}</span><strong>{value}<small>{unit}</small></strong></div>)}</div>
 <LiveAgentConsole coinId={coin.id} t={t}/>
 <Tabs defaultValue="overview" className="token-tabs"><TabsList><TabsTrigger value="overview">{t("概览","Overview")}</TabsTrigger><TabsTrigger value="chat">{t("对话","Chat")}</TabsTrigger><TabsTrigger value="treasury">{t("收益与成本","Revenue")}</TabsTrigger><TabsTrigger value="activity">{t("动态","Activity")}</TabsTrigger><TabsTrigger value="research">{t("研究","Research")}</TabsTrigger><TabsTrigger value="community">{t("社区","Community")}</TabsTrigger><TabsTrigger value="website">{t("网站","Website")}</TabsTrigger></TabsList>
 <TabsContent value="overview"><div className="panel chart-panel"><div className="panel-heading"><h2>{t("价格图表","Price chart")}</h2><span className="overline">5M</span></div>{launched?<TokenChart coinId={coin.id} t={t}/>:<div className="empty-state"><Activity size={27}/><h3>{t("等待发行","Awaiting launch")}</h3><p>{t("有已索引的交易后显示蜡烛图。","Candles appear when indexed trades are available.")}</p></div>}</div><div className="panel agent-mission"><span className="overline accent">{t("开发者定义的使命","DEVELOPER-DEFINED MISSION")}</span><h2>{t("自主行动，有明确方向。","A mind with a purpose.")}</h2><p>{coin.purpose??DEFAULT_AGENT_PURPOSE}</p>{(coin.personality||coin.focus)&&<dl className="character-summary">{coin.personality&&<><dt>{t("表达风格","Voice")}</dt><dd>{characterLabel(coin.personality,VOICES,t)}</dd></>}{coin.focus&&<><dt>{t("关注方向","Focus")}</dt><dd>{characterLabel(coin.focus,FOCUSES,t)}</dd></>}</dl>}<div><ModelLogo modelId={coin.modelId} size={24}/><strong>{agentModel(coin.modelId).name}</strong><span>{t("创建时由开发者选择","Selected by the developer at launch")}</span></div></div><div className="panel"><div className="panel-heading"><h2>{t("智能体能力","Agent capabilities")}</h2></div><div className="feature-grid">{[[Search,t("网络研究","Web research"),coin.research],[Radio,t("社区更新","Community updates"),coin.social],[ImageIcon,t("图片生成","Image generation"),coin.images],[Globe2,t("社区网站","Community website"),coin.website]].map(([Icon,label,on])=>{const I=Icon as typeof Search;return <div className="feature" key={String(label)}><I size={21}/><strong>{String(label)}</strong><span>{on?t("使命的一部分","Part of its mission"):t("未选择","Not selected")}</span></div>})}</div></div></TabsContent>
 <TabsContent value="chat"><AgentChat coin={coin} t={t}/></TabsContent>
 <TabsContent value="treasury"><div className="panel"><div className="panel-heading"><h2>{t("全部收益，由智能体管理。","One treasury. Agent-managed revenue.")}</h2></div><div className="allocation-bar"><i style={{width:"100%"}}/></div><div className="allocation-row"><span>{t("智能体金库","Agent treasury")}</span><strong>85% / 15% SHEN</strong></div><p className="body-copy">{t("平台保留已确认费用的 15% 自动回购并销毁 SHEN。其余 85% 先支付计算、搜索、X、托管、域名与燃料成本。再根据实际可用资金决定社区与代币支出。","15% of confirmed fee revenue is reserved for automatic SHEN buybacks and burns. The remaining 85% covers compute, research, X, hosting, domains and gas first. Community and token spending depends on the funds remaining.")}</p>{coin.treasuryAddress&&<a className="text-link address-link" href={"https://bscscan.com/address/"+coin.treasuryAddress} target="_blank" rel="noreferrer">{coin.treasuryAddress} <ExternalLink size={14}/></a>}</div>{launched&&<ProtocolFees coinId={coin.id} t={t}/>} {launched&&<TreasuryOperations coinId={coin.id} symbol={coin.symbol} t={t}/>}</TabsContent>
 <TabsContent value="activity"><div className="panel"><div className="panel-heading"><h2>{t("智能体日志","Agent log")}</h2></div>{events.length?<div className="timeline">{events.map(e=><div className="timeline-row" key={e.id}><span className="timeline-symbol"><Activity size={16}/></span><div><span className="overline">{new Date(e.createdAt).toLocaleString()}</span><p>{e.message}</p></div></div>)}</div>:<div className="empty-state"><Activity/><p>{eventError||t("尚无已记录的活动。","No recorded activity yet.")}</p></div>}</div></TabsContent>
 <TabsContent value="research"><ResearchFeed coinId={coin.id} enabled={coin.research} t={t}/></TabsContent>
 <TabsContent value="community"><CommunityFeed coinId={coin.id} t={t}/></TabsContent><TabsContent value="website"><AgentWebsite coin={coin} t={t}/></TabsContent></Tabs>
 {canManage&&coin.social&&<SocialConnection coinId={coin.id} t={t}/>}{canManage&&!launched&&<div id="flap-launch"><FlapLaunch coin={coin} onConfirmed={setCoin}/></div>}</div>
 <aside className="agent-console panel"><div className="console-heading"><Bot size={20}/><h2>{t("智能体状态","Agent status")}</h2></div><div className="console-status"><span className="overline">CURRENT STATE</span><strong>{stateLabel(coin,t)}</strong><p>{launched?t("自动检查资金与服务状态。","Activity depends on available funding and service readiness."):t("等待链上发行确认。","Awaiting an on-chain launch confirmation.")}</p></div><div className="console-settings"><div><span>{t("模型","Model")}</span><strong className="model-label"><ModelLogo modelId={coin.modelId} size={20}/>{agentModel(coin.modelId).name}</strong></div><div><span>{t("语言","Language")}</span><strong>{coin.language==="zh"?"中文":"English"}</strong></div><div><span>{t("支出模式","Spending")}</span><strong>{t("动态调整","Adaptive")}</strong></div></div>{launched&&<div className="permanent-agent"><ShieldCheck size={17}/><div><strong>{t("开发者控制权已锁定","Developer controls locked")}</strong><p>{t("发行后，开发者无法暂停或恢复智能体。","The developer cannot pause or resume this agent after launch.")}</p></div></div>}<div className="console-note"><ShieldCheck size={17}/><p>{t("先支付服务成本。透明记录决策，不承诺收益。","Service costs first. Transparent decisions, no return promises.")}</p></div></aside></div></>
}
