import { sqliteTable, text, integer, uniqueIndex, index } from "drizzle-orm/sqlite-core";
export const coins = sqliteTable("coins", {id:text("id").primaryKey(),owner:text("owner").notNull(),config:text("config").notNull(),tokenAddress:text("token_address"),treasuryAddress:text("treasury_address"),createdAt:text("created_at").notNull(),updatedAt:text("updated_at").notNull(),aiCreditMicrousd:integer("ai_credit_microusd").notNull().default(0),dailyLimitMicrousd:integer("daily_limit_microusd").notNull().default(100000)},t=>[index("coins_owner_idx").on(t.owner),uniqueIndex("coins_token_unique").on(t.tokenAddress),uniqueIndex("coins_treasury_unique").on(t.treasuryAddress)]);
export const events=sqliteTable("events",{id:text("id").primaryKey(),coinId:text("coin_id").notNull().references(()=>coins.id),owner:text("owner").notNull(),name:text("name").notNull(),message:text("message").notNull(),createdAt:text("created_at").notNull()},t=>[index("events_owner_time_idx").on(t.owner,t.createdAt)]);
export const runs=sqliteTable("agent_runs",{id:text("id").primaryKey(),coinId:text("coin_id").notNull().references(()=>coins.id),kind:text("kind").notNull(),status:text("status").notNull(),reservedMicrousd:integer("reserved_microusd").notNull(),costMicrousd:integer("cost_microusd"),output:text("output"),createdAt:text("created_at").notNull(),finishedAt:text("finished_at")},t=>[index("runs_coin_time_idx").on(t.coinId,t.createdAt)]);
export const launchPlans=sqliteTable("launch_plans",{coinId:text("coin_id").primaryKey().references(()=>coins.id),creator:text("creator").notNull(),treasury:text("treasury").notNull(),calldata:text("calldata").notNull(),predictedAddress:text("predicted_address").notNull(),cid:text("cid").notNull(),createdAt:text("created_at").notNull(),txHash:text("tx_hash")});
export const preparedLaunches=sqliteTable("prepared_launches",{id:text("id").primaryKey(),coinId:text("coin_id").notNull().references(()=>coins.id),creator:text("creator").notNull(),treasury:text("treasury").notNull(),calldata:text("calldata").notNull(),predictedAddress:text("predicted_address").notNull(),cid:text("cid").notNull(),createdAt:text("created_at").notNull(),txHash:text("tx_hash")},t=>[index("prepared_launches_coin_idx").on(t.coinId)]);
export const chatRuns=sqliteTable("chat_runs",{id:text("id").primaryKey(),coinId:text("coin_id").notNull().references(()=>coins.id),viewer:text("viewer").notNull(),status:text("status").notNull(),reservedMicrousd:integer("reserved_microusd").notNull(),costMicrousd:integer("cost_microusd"),createdAt:integer("created_at").notNull()},t=>[index("chat_runs_coin_time_idx").on(t.coinId,t.createdAt),index("chat_runs_viewer_time_idx").on(t.viewer,t.createdAt),index("chat_runs_time_idx").on(t.createdAt)]);
// Only the trusted payment reconciler may insert confirmed funding receipts.
// No browser endpoint can create these rows or grant compute credit.
export const computeFunding=sqliteTable("compute_funding",{settlementId:text("settlement_id").primaryKey(),coinId:text("coin_id").notNull().references(()=>coins.id),amountMicrousd:integer("amount_microusd").notNull(),settledAt:integer("settled_at").notNull(),valuation:text("valuation")},t=>[index("funding_coin_time_idx").on(t.coinId,t.settledAt)]);
export const agentChatControl=sqliteTable("agent_chat_control",{coinId:text("coin_id").primaryKey().references(()=>coins.id),closedUntil:integer("closed_until").notNull()});
export const marketCache=sqliteTable("market_cache",{tokenAddress:text("token_address").primaryKey(),body:text("body").notNull(),expiresAt:integer("expires_at").notNull()});
export const providerLimits=sqliteTable("provider_limits",{id:text("id").primaryKey(),nextAt:integer("next_at").notNull()});
export const agentWallets=sqliteTable("agent_wallets",{coinId:text("coin_id").primaryKey().references(()=>coins.id),address:text("address").notNull(),createdAt:integer("created_at").notNull()},t=>[uniqueIndex("agent_wallet_address_unique").on(t.address)]);
export const launchAuthorizations=sqliteTable("launch_authorizations",{id:text("id").primaryKey(),coinId:text("coin_id").notNull().references(()=>coins.id),creator:text("creator").notNull(),treasury:text("treasury").notNull(),message:text("message").notNull(),configHash:text("config_hash").notNull(),expiresAt:integer("expires_at").notNull(),usedAt:integer("used_at")},t=>[index("launch_auth_coin_idx").on(t.coinId)]);
export const runtimeHealth=sqliteTable("runtime_health",{id:text("id").primaryKey(),checkedAt:integer("checked_at").notNull(),capabilities:text("capabilities").notNull(),version:text("version").notNull()});
export const runtimeLeases=sqliteTable("runtime_leases",{coinId:text("coin_id").primaryKey().references(()=>coins.id),leaseId:text("lease_id"),leaseUntil:integer("lease_until").notNull().default(0),nextRunAt:integer("next_run_at").notNull().default(0)});
export const walletChallenges=sqliteTable("wallet_challenges",{id:text("id").primaryKey(),wallet:text("wallet").notNull(),message:text("message").notNull(),expiresAt:integer("expires_at").notNull(),consumed:integer("consumed").notNull().default(0)},t=>[index("wallet_challenge_expiry_idx").on(t.expiresAt),index("wallet_challenge_wallet_idx").on(t.wallet)]);
export const walletSessions=sqliteTable("wallet_sessions",{id:text("id").primaryKey(),wallet:text("wallet").notNull(),expiresAt:integer("expires_at").notNull()},t=>[index("wallet_session_expiry_idx").on(t.expiresAt)]);
export const coinImages=sqliteTable("coin_images",{coinId:text("coin_id").primaryKey().references(()=>coins.id),mime:text("mime").notNull(),base64:text("base64").notNull()});
export const xAccounts=sqliteTable("x_accounts",{coinId:text("coin_id").primaryKey().references(()=>coins.id),userId:text("user_id").notNull(),username:text("username").notNull(),encryptedSession:text("encrypted_session").notNull(),version:text("version").notNull(),updatedAt:integer("updated_at").notNull()},t=>[uniqueIndex("x_account_user_unique").on(t.userId)]);
export const xLogins=sqliteTable("x_logins",{id:text("id").primaryKey(),coinId:text("coin_id").notNull().references(()=>coins.id),owner:text("owner").notNull(),userId:text("user_id"),username:text("username").notNull(),encryptedSession:text("encrypted_session"),proof:text("proof").notNull(),tweetId:text("tweet_id"),status:text("status").notNull(),costMicrousd:integer("cost_microusd").notNull(),checks:integer("checks").notNull().default(0),createdAt:integer("created_at").notNull()},t=>[index("x_login_owner_idx").on(t.owner,t.createdAt)]);
export const contentJobs=sqliteTable("content_jobs",{id:text("id").primaryKey(),coinId:text("coin_id").notNull().references(()=>coins.id),payload:text("payload").notNull(),status:text("status").notNull(),quote:text("quote"),userId:text("user_id"),mediaId:text("media_id"),tweetId:text("tweet_id"),reservedMicrousd:integer("reserved_microusd").notNull().default(0),costMicrousd:integer("cost_microusd").notNull().default(0),attempts:integer("attempts").notNull().default(0),postingAt:integer("posting_at"),nextAttemptAt:integer("next_attempt_at").notNull().default(0),createdAt:integer("created_at").notNull(),updatedAt:integer("updated_at").notNull()},t=>[index("content_jobs_status_idx").on(t.status,t.updatedAt),index("content_jobs_coin_idx").on(t.coinId,t.createdAt)]);
export const contentAssets=sqliteTable("content_assets",{id:text("id").primaryKey().references(()=>contentJobs.id),coinId:text("coin_id").notNull().references(()=>coins.id),mime:text("mime").notNull(),base64:text("base64").notNull(),model:text("model").notNull(),altText:text("alt_text").notNull(),createdAt:integer("created_at").notNull()});
export const agentOperations=sqliteTable("agent_operations",{id:text("id").primaryKey(),coinId:text("coin_id").notNull().references(()=>coins.id),kind:text("kind").notNull(),amountWei:text("amount_wei").notNull(),reservedMicrousd:integer("reserved_microusd").notNull().default(0),status:text("status").notNull(),txHash:text("tx_hash"),expiresAt:integer("expires_at").notNull(),createdAt:integer("created_at").notNull(),reason:text("reason").notNull(),details:text("details")},t=>[index("operations_status_idx").on(t.status,t.createdAt),uniqueIndex("operation_tx_unique").on(t.txHash)]);
export const siteRevisions=sqliteTable('site_revisions',{id:text('id').primaryKey(),coinId:text('coin_id').notNull().references(()=>coins.id),revision:integer('revision').notNull(),content:text('content').notNull(),publishedAt:integer('published_at').notNull()},t=>[uniqueIndex('site_revision_unique').on(t.coinId,t.revision)]);
export const treasuryObservations=sqliteTable('treasury_observations',{id:text('id').primaryKey(),coinId:text('coin_id').notNull().references(()=>coins.id),processor:text('processor').notNull(),blockNumber:text('block_number').notNull(),blockHash:text('block_hash').notNull(),observedAt:integer('observed_at').notNull(),balanceWei:text('balance_wei').notNull(),cumulativeFeesWei:text('cumulative_fees_wei').notNull(),pendingFeesWei:text('pending_fees_wei').notNull()},t=>[uniqueIndex('treasury_observation_block').on(t.coinId,t.blockNumber),index('treasury_observation_time').on(t.coinId,t.observedAt)]);

export const domainOrders=sqliteTable('domain_orders',{id:text('id').primaryKey(),coinId:text('coin_id').notNull().references(()=>coins.id),domain:text('domain').notNull(),kind:text('kind').notNull(),payload:text('payload').notNull(),status:text('status').notNull(),costCents:integer('cost_cents').notNull().default(0),fundingCents:integer('funding_cents').notNull().default(0),minimumCreditCents:integer('minimum_credit_cents').notNull().default(0),creditCents:integer('credit_cents').notNull().default(0),reservedCents:integer('reserved_cents').notNull().default(0),chargedCents:integer('charged_cents').notNull().default(0),fundingExpiresAt:integer('funding_expires_at'),checkoutId:text('checkout_id'),purchaseStartedAt:integer('purchase_started_at'),purchaseAttempts:integer('purchase_attempts').notNull().default(0),providerOrder:text('provider_order'),routeAttempted:integer('route_attempted').notNull().default(0),deployAttempted:integer('deploy_attempted').notNull().default(0),nextAttemptAt:integer('next_attempt_at').notNull().default(0),lastError:text('last_error'),createdAt:integer('created_at').notNull(),updatedAt:integer('updated_at').notNull()},t=>[index('domain_order_due').on(t.status,t.nextAttemptAt),index('domain_order_coin').on(t.coinId,t.createdAt),uniqueIndex('domain_checkout_unique').on(t.checkoutId)]);
export const coinDomains=sqliteTable('coin_domains',{coinId:text('coin_id').primaryKey().references(()=>coins.id),domain:text('domain').notNull(),state:text('state').notNull(),verificationToken:text('verification_token').notNull(),expiresAt:integer('expires_at'),orderId:text('order_id').notNull().references(()=>domainOrders.id),lastError:text('last_error'),updatedAt:integer('updated_at').notNull()},t=>[uniqueIndex('coin_domain_unique').on(t.domain)]);
export const domainControl=sqliteTable('domain_control',{id:text('id').primaryKey(),leaseId:text('lease_id'),leaseUntil:integer('lease_until').notNull().default(0)});

export const curveCursors=sqliteTable('curve_cursors',{coinId:text('coin_id').primaryKey().references(()=>coins.id),tokenAddress:text('token_address').notNull(),launchHash:text('launch_hash').notNull(),nextBlock:integer('next_block').notNull(),startBlock:integer('start_block').notNull(),lastHash:text('last_hash'),leaseId:text('lease_id'),leaseUntil:integer('lease_until').notNull().default(0),checkedAt:integer('checked_at').notNull().default(0),indexedAt:integer('indexed_at').notNull().default(0),migrated:integer('migrated').notNull().default(0),caughtUp:integer('caught_up').notNull().default(0),rangeSize:integer('range_size').notNull().default(2000)},t=>[uniqueIndex('curve_token_unique').on(t.tokenAddress)]);
export const curveTrades=sqliteTable('curve_trades',{id:text('id').primaryKey(),coinId:text('coin_id').notNull().references(()=>coins.id),blockNumber:integer('block_number').notNull(),blockHash:text('block_hash').notNull(),time:integer('time').notNull(),logIndex:integer('log_index').notNull(),tokenWei:text('token_wei').notNull(),quoteWei:text('quote_wei').notNull(),side:text('side').notNull(),txHash:text('tx_hash').notNull()},t=>[index('curve_trade_time').on(t.coinId,t.time),index('curve_trade_block').on(t.coinId,t.blockNumber)]);
